/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Bookings: () => import('#controllers/bookings_controller'),
  Customers: () => import('#controllers/customers_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Sessions: () => import('#controllers/sessions_controller'),
}
