/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AgentBookingReschedules: () => import('#controllers/agent_booking_reschedules_controller'),
  AgentBookingSearches: () => import('#controllers/agent_booking_searches_controller'),
  ApprovalDecisions: () => import('#controllers/approval_decisions_controller'),
  ApprovalRequests: () => import('#controllers/approval_requests_controller'),
  Bookings: () => import('#controllers/bookings_controller'),
  ConversationMessages: () => import('#controllers/conversation_messages_controller'),
  Customers: () => import('#controllers/customers_controller'),
  DemoSessions: () => import('#controllers/demo_sessions_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Sessions: () => import('#controllers/sessions_controller'),
  SupportConversations: () => import('#controllers/support_conversations_controller'),
}
