/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class BookingSchema extends BaseModel {
  static $columns = ['createdAt', 'customerId', 'durationMinutes', 'id', 'scheduledAt', 'service', 'serviceAddress', 'staff', 'status', 'updatedAt'] as const
  $columns = BookingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: number
  @column()
  declare durationMinutes: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare scheduledAt: DateTime
  @column()
  declare service: string
  @column()
  declare serviceAddress: string
  @column()
  declare staff: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CustomerSchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'email', 'id', 'name', 'notes', 'phone', 'updatedAt'] as const
  $columns = CustomerSchema.$columns
  @column()
  declare address: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare notes: string
  @column()
  declare phone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SupportConversationSchema extends BaseModel {
  static $columns = ['createdAt', 'customerId', 'firstMessageAt', 'id', 'lastMessagePreview', 'status', 'title', 'updatedAt'] as const
  $columns = SupportConversationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: number
  @column.dateTime()
  declare firstMessageAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lastMessagePreview: string | null
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
