/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class BookingRescheduleGrantSchema extends BaseModel {
  static $columns = ['bookingId', 'createdAt', 'customerId', 'expectedStartTime', 'expiresAt', 'proposedStartTime', 'runId', 'toolCallId', 'updatedAt'] as const
  $columns = BookingRescheduleGrantSchema.$columns
  @column()
  declare bookingId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: number
  @column.dateTime()
  declare expectedStartTime: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column.dateTime()
  declare proposedStartTime: DateTime
  @column()
  declare runId: string
  @column({ isPrimary: true })
  declare toolCallId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BookingSchema extends BaseModel {
  static $columns = ['createdAt', 'customerId', 'durationMinutes', 'id', 'scheduledAt', 'service', 'serviceAddress', 'staff', 'status', 'updatedAt'] as const
  $columns = BookingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: number
  @column()
  declare durationMinutes: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare scheduledAt: DateTime
  @column()
  declare service: string
  @column()
  declare serviceAddress: string
  @column()
  declare staff: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CustomerEmailVerificationSchema extends BaseModel {
  static $columns = ['codeHash', 'createdAt', 'customerId', 'email', 'expiresAt', 'failedAttempts', 'id', 'name', 'visitorId'] as const
  $columns = CustomerEmailVerificationSchema.$columns
  @column()
  declare codeHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: number | null
  @column()
  declare email: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare failedAttempts: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string | null
  @column()
  declare visitorId: string | null
}

export class CustomerSchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'email', 'emailVerifiedAt', 'id', 'name', 'notes', 'phone', 'updatedAt'] as const
  $columns = CustomerSchema.$columns
  @column()
  declare address: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare notes: string
  @column()
  declare phone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InboxAnnotationSchema extends BaseModel {
  static $columns = ['conversationId', 'createdAt', 'detail', 'id', 'kind', 'summary'] as const
  $columns = InboxAnnotationSchema.$columns
  @column()
  declare conversationId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare detail: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare kind: string
  @column()
  declare summary: string
}

export class InboxAttentionItemSchema extends BaseModel {
  static $columns = ['actionType', 'cause', 'contextJson', 'conversationId', 'createdAt', 'decidedAt', 'decidedByUserId', 'externalKey', 'id', 'outcomeSummary', 'status', 'summary', 'updatedAt'] as const
  $columns = InboxAttentionItemSchema.$columns
  @column()
  declare actionType: string
  @column()
  declare cause: string
  @column()
  declare contextJson: string
  @column()
  declare conversationId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare decidedAt: DateTime | null
  @column()
  declare decidedByUserId: number | null
  @column()
  declare externalKey: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare outcomeSummary: string | null
  @column()
  declare status: string
  @column()
  declare summary: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SupportConversationSchema extends BaseModel {
  static $columns = ['createdAt', 'customerId', 'firstMessageAt', 'handlingMode', 'id', 'lastMessagePreview', 'memoryResourceId', 'nextStepOwner', 'outcomeStatus', 'outcomeSummary', 'status', 'title', 'updatedAt', 'visitorId'] as const
  $columns = SupportConversationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: number | null
  @column.dateTime()
  declare firstMessageAt: DateTime | null
  @column()
  declare handlingMode: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lastMessagePreview: string | null
  @column()
  declare memoryResourceId: string
  @column()
  declare nextStepOwner: string
  @column()
  declare outcomeStatus: string
  @column()
  declare outcomeSummary: string | null
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare visitorId: string | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
